#number of total: 10679
mv -i data/dmnYesHasInsTrain/genYes1720-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes506-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1182-23-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes75-20-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes35-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes649-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1204-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1278-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1576-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1481-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes96-15-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes516-120-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes135-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes242-21-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes527-240-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1353-21-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes799-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes649-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1030-16-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes601-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes366-16-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-240-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes902-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1774-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1761-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes328-41-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1623-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes712-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1767-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1163-14-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes78-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-200-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes571-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes113-38-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1638-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1416-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes305-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1470-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1362-261-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes762-31-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1538-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes717-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1105-139-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1397-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes501-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes621-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1483-29-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes988-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1384-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes624-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1428-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1383-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes69-64-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1475-25-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes279-12-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1383-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes690-13-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1597-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/20150310133609_263_13255716885_52074.wav.txt data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1564-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1727-15-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes775-25-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1632-22-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1454-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1743-129-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes414-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1934-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1922-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes723-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1511-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1184-36-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes36-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes879-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes461-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes398-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1673-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1849-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes493-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1788-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes16-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1365-46-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1309-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-480-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes614-20-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes716-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1772-34-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1847-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes680-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes10-107-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes358-20-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes19-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1362-240-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1954-58-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes259-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1023-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes609-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1895-76-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1009-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1581-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1037-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1448-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes689-23-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1356-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes198-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1940-17-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes693-15-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1909-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes86-12-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes285-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1246-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1828-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes784-160-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1627-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes265-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes13-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes818-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes428-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1275-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes40-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1436-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes415-240-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1621-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1198-18-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes533-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-120-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1160-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1580-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1642-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1131-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1210-38-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes687-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1182-23-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1059-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes881-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1596-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes156-320-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1895-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes949-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1899-124-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes573-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1309-120-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1703-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes422-319-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes172-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes813-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes649-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes183-78-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1775-23-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes111-38-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes698-320-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes228-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1408-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes146-15-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1303-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1086-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1787-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes595-28-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes299-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes209-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes982-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes259-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1362-261-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1364-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-320-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1121-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes865-19-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1187-210-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1824-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes218-38-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1844-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes171-67-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1463-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1714-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes244-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1473-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1561-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-234-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes786-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1806-29-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1939-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-240-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes422-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes383-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes223-2-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes98-17-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1774-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes780-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes516-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1924-18-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes964-21-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1868-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes5-200-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes150-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1800-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes481-200-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes384-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes779-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-480-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1323-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1899-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes324-129-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes566-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1904-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes691-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1051-38-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes927-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes860-96-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes617-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1709-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-363-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes852-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1451-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1172-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1906-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1615-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes899-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes661-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1137-160-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1858-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes343-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes241-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1669-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1205-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1726-24-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes315-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1575-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1443-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-480-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes701-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1114-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1094-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes627-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1441-34-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1828-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes399-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes784-174-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes501-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1392-24-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1036-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes294-59-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1651-25-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1492-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1412-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes691-18-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes483-20-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes576-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1649-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1540-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1362-120-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1815-17-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1179-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1466-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1827-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1262-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1360-24-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes753-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes102-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes255-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes67-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1957-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1899-124-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes639-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes964-21-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1961-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes912-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1340-22-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes231-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes917-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1818-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1253-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes971-21-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1348-20-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes974-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-323-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1170-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1607-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes819-12-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1649-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1643-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1071-38-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes90-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes600-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes761-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes710-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes400-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes246-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes784-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes339-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes134-20-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes458-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes972-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1522-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-160-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1499-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes867-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes266-26-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1423-154-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes993-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes432-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1886-12-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1698-28-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1706-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1304-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes516-178-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1819-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1439-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes655-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1347-35-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1540-280-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1593-38-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes627-120-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes105-29-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes931-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes719-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1047-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1047-280-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1884-23-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes360-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes599-20-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1130-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1247-2-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes522-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes63-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1085-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1838-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes715-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes862-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes671-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1148-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1025-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1515-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes334-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1069-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1314-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes212-160-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1580-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes412-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes235-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes171-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes746-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-440-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1516-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1637-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes171-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes698-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1919-16-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1470-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1092-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes908-18-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes118-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1200-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1144-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1532-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes193-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1003-20-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes478-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1582-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1692-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes696-22-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes641-220-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1086-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1113-18-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1442-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes629-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1476-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes149-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes743-16-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes514-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes188-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1355-13-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes861-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1093-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes541-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1187-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1112-38-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1592-50-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1260-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1356-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1666-18-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes620-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes647-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes833-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes570-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1168-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-160-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1006-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1389-23-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1742-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1650-16-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes415-160-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1956-22-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes121-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1795-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes916-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes379-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes535-22-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1091-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1076-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1454-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes76-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes916-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1187-160-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes459-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1362-240-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes888-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1953-75-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1717-16-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-240-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes88-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1352-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1380-22-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1946-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1719-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes756-26-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1705-15-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1546-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1877-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes919-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-240-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes965-176-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes198-62-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1516-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes749-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes857-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes308-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-440-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1119-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes28-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes863-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes9-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1163-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes81-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes216-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1226-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1137-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes619-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1518-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1213-11-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1540-400-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1943-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes642-30-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes115-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1793-100-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes156-200-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-200-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1074-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1799-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes661-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes395-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes294-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1133-20-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes698-357-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1412-128-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1295-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes883-20-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-240-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes579-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes296-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1642-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes275-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1086-240-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1240-11-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes633-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes862-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes616-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1187-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1841-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1895-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes769-15-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1931-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-480-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1246-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes153-13-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1555-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes311-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes889-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1014-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1878-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1464-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes651-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1301-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1576-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes242-21-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes929-24-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes514-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1292-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes739-120-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes747-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1545-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes248-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes185-34-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes134-20-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes189-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes493-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-120-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1004-21-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-240-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1831-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes849-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1556-19-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1908-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1604-160-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1332-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1399-18-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1171-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes681-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1337-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1855-160-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1541-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1448-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1526-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes874-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes168-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1085-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1660-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes657-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes855-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes672-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1749-22-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1917-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-320-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes721-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes820-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes397-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes631-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1292-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes936-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1547-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1181-17-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes221-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes53-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes195-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-560-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes67-120-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1469-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1560-22-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes354-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes415-280-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes564-32-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1002-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1866-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1880-15-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes420-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1181-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1021-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes184-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes117-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes370-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes816-54-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes719-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1649-13-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes254-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes906-16-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes130-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1877-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes415-200-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1921-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes497-27-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1250-23-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes136-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1393-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1610-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1793-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes661-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes154-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1428-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes949-41-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1508-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes416-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1755-22-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/20150122151759_1050_13511263217_55112.wav.txt data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes238-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1680-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-160-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1204-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes874-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes861-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1778-240-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1273-27-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes894-240-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes600-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes20-23-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1757-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1302-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1792-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1876-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1849-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes717-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1578-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes5-160-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1784-13-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1052-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1171-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes423-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes849-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes447-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes564-32-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes651-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1562-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes299-94-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1150-18-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes413-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes607-19-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1540-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes289-26-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes237-17-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1394-38-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1228-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1797-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1187-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1047-324-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes800-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1622-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes644-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1425-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes706-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1489-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1933-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes119-76-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes717-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes375-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes8-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1490-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes399-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1580-193-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes132-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes626-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1084-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes290-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1362-261-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes183-78-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1849-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1363-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes262-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1405-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes785-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1403-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes78-90-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1710-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1221-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes692-20-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes156-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1292-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1819-90-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1252-37-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1610-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes159-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes473-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1547-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1973-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes338-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes86-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-160-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1743-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1267-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1707-22-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes263-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes277-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes769-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1048-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1907-20-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1910-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes415-240-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1160-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-200-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1656-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1374-28-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1362-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1259-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1461-29-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes411-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1077-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-360-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes450-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1222-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes570-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes935-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes68-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1109-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1100-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-440-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes199-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1095-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes630-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1323-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes205-28-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes89-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes274-21-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1752-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes541-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes718-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes350-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes217-26-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1451-13-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1104-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1447-53-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1846-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes519-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1382-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1667-16-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1557-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1828-120-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1679-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes481-120-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1320-16-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes233-26-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes551-15-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1388-18-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes346-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1355-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-360-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1793-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes496-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes644-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1603-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes77-49-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1090-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1551-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes529-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1255-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes254-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes216-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1061-38-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes644-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes527-280-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes222-63-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1743-129-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1150-18-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes212-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-280-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-280-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes768-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes965-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes276-21-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1425-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes769-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1420-14-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes177-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1562-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes207-29-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes340-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes967-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1700-22-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1635-38-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes533-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes83-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes323-16-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes361-23-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes570-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes701-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1826-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes116-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes266-26-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes523-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1140-17-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-520-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes544-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1813-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes689-23-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1053-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1205-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes725-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1969-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes995-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes284-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes908-18-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes904-27-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1136-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1255-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1540-200-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1957-17-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes354-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1766-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1336-23-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes480-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes390-19-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1019-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes948-16-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes970-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1838-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1919-16-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes82-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1902-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes816-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1430-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1960-17-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes990-19-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes382-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-400-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-440-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes755-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1105-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1423-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1249-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes890-43-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes72-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes900-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes626-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes249-14-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1569-2-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1376-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1113-18-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1635-38-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1233-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-360-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1584-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1912-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-520-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes838-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes769-15-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1847-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes292-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes82-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes358-20-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1220-19-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes865-19-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1792-11-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1468-24-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes818-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1145-125-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1719-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes466-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1107-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1564-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes305-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes637-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes834-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1535-30-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes316-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes324-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1414-29-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1431-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1314-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes355-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1230-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes646-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes132-224-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1041-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes890-43-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes154-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes726-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes415-200-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1526-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1633-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1778-280-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1554-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1519-21-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes696-22-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes219-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1497-26-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes621-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1111-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1362-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes108-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1218-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1183-71-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1550-19-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1335-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes612-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1835-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-520-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1843-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1208-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes623-19-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes734-19-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1615-15-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes261-16-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-480-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1897-23-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1480-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes774-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1293-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes151-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1912-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes324-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1942-30-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes29-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes772-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes156-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1148-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes159-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1826-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1774-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes818-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-200-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1127-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes563-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes673-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1936-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes789-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes639-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1917-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes644-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes213-18-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes138-16-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes541-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1107-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes819-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes895-26-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes834-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1915-200-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes25-25-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes625-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1112-38-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1047-320-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1540-200-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes731-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes271-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1894-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1787-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1122-19-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes368-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1917-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1486-30-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes570-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes522-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes732-20-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1337-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes28-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1705-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes962-17-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes858-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes422-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1778-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1648-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes349-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes313-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes779-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1701-30-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1231-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes774-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1233-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes576-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1143-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1513-19-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1460-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1581-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1217-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1465-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes334-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes762-31-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1289-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes440-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes276-21-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes729-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes154-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes127-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/TEL-04768277355_5860065584_20150319163554.wav.txt data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1423-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1348-20-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1769-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes611-23-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes136-17-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes155-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes662-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1072-38-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1610-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes728-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes590-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes73-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes641-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes57-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1883-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes980-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes65-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1097-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1523-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1072-38-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes916-160-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes960-12-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1743-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes185-34-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1792-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes691-18-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes176-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes94-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1300-15-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes77-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes554-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes612-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1388-18-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-539-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes78-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes174-26-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1522-41-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes506-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-200-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes711-16-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1362-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1069-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes215-18-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1277-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1267-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1152-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes315-160-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes288-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1644-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes955-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1769-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes193-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes156-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1189-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1521-16-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1882-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1657-18-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes877-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1761-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes186-38-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes130-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1788-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes437-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes783-25-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1527-17-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1290-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes291-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes600-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1596-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes322-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes481-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1111-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes947-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1855-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes641-160-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1970-55-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes363-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1145-120-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1854-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1074-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes485-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1371-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1215-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes298-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1888-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1466-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1968-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes23-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1646-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes607-19-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1384-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1030-16-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes367-24-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes371-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes922-21-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes243-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1919-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1287-154-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1935-10-2 data/dmnYesHasInsEval
