#number of total: 11980
mv -i data/dmnYesHasInsTrain/genYes1839-68-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1735-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1967-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes79-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1180-25-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes996-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes367-24-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1199-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1166-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-280-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1404-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes39-20-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1187-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes641-160-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1622-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-480-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes164-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes689-23-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes852-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes785-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1388-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1007-360-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes90-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1701-30-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1586-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1272-19-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1875-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1302-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes290-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes426-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1773-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes864-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes785-45-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes593-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1434-22-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes165-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1117-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1849-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes691-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes862-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes990-19-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes5-240-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1137-245-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes669-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1170-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes873-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes97-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1499-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes793-18-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1331-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes763-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes649-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1055-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes356-19-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes95-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes48-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1589-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1740-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1648-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes130-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1206-21-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes361-23-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes507-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1137-240-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1329-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes204-14-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes212-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1084-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1093-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes68-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1778-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes673-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1447-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1393-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1140-17-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes934-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1211-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes86-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1895-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1403-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes965-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-323-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1754-22-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes535-22-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1862-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes149-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes342-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes317-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes189-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes0-24-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1668-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1751-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1319-23-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1678-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes583-34-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes453-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes777-17-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1216-13-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes683-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes580-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes990-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1585-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1496-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes453-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1219-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes393-32-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes942-35-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes685-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1464-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1447-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-600-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes26-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes279-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1763-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes216-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1534-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1871-17-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes894-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1808-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1822-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1506-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes329-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes81-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1747-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1534-120-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes224-20-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1077-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes489-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-676-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1389-23-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1100-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes53-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-240-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes383-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-200-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1789-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1003-20-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1669-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes77-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1489-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1547-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes40-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes5-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1265-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1395-34-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1949-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1395-34-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1055-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes464-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1384-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1819-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1610-147-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1835-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1537-34-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-280-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes548-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1135-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1173-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1205-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes750-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1305-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes744-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1425-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1347-35-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1322-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes255-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes117-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes89-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes213-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1090-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-280-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes852-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes845-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes625-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes573-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1908-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-120-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes265-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes406-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1282-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes627-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1567-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes749-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1418-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes357-17-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes376-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1915-202-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1238-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1719-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1681-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1150-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1415-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1448-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1539-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1396-32-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes481-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes616-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1122-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1596-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1460-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes387-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-200-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes383-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes445-29-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1113-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes501-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1485-12-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1610-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1187-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes481-240-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes301-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1207-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes210-13-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes239-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1755-22-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes629-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1443-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes37-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1379-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes887-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1111-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes340-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes69-64-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes916-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1915-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1285-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1040-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes496-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes268-24-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1675-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1772-34-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1519-21-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1557-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1076-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes504-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes855-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1016-81-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes958-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1524-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1512-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1289-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1099-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes553-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes216-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes351-21-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes72-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1511-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-200-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes269-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes597-38-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes969-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1792-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1556-19-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-320-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1354-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1298-20-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes752-16-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes169-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1758-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1157-19-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1309-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes132-224-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1419-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes203-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1803-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-360-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes440-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes681-118-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1900-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1941-17-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes5-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1428-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1589-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1143-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes619-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1050-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes376-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1883-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1432-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1129-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes367-24-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1733-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes849-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes184-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1103-22-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes374-28-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes923-16-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1480-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1338-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1775-23-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-280-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1481-12-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1968-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes898-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1595-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes434-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1972-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1729-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes302-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1788-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1850-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes902-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes5-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1479-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1862-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1309-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes106-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1236-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1154-16-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1636-38-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes664-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes738-28-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1751-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes618-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1385-29-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-320-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1215-64-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes170-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1385-29-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes209-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1057-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1828-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1020-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes617-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1963-22-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes989-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes79-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes150-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1534-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes504-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1007-363-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1773-41-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1502-38-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes415-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes843-27-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1723-22-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1024-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1412-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1656-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1566-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes318-38-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1442-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes816-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes994-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes740-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes560-22-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1602-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes926-16-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1624-25-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1016-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes894-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1774-187-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1043-23-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes225-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes323-16-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes910-38-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes859-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes86-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes182-22-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1623-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes82-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes288-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1653-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1026-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1581-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-360-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1762-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes156-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1413-38-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes460-440-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes550-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1571-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1353-21-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1749-22-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1955-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes181-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes687-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1126-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes212-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1318-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-280-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1798-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes158-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes705-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1804-36-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1715-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes659-22-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes915-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes330-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes623-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1913-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1105-139-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1700-22-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes144-23-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes418-21-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1088-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1901-13-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1086-240-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1766-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1882-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes968-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1646-93-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1913-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes698-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1487-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1288-67-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1910-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes481-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes338-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1689-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1019-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1491-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes167-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1941-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1030-16-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes252-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes652-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1589-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes154-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1729-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes119-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1234-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1717-16-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes356-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes540-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes778-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes874-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes168-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes88-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes107-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes299-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes872-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1679-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes357-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1255-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1704-23-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes588-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes313-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1340-22-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1131-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-360-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes641-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1877-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1774-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1042-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1602-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes727-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1645-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1570-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1171-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1362-261-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes865-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1868-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1062-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1691-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes92-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1221-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1892-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes132-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes372-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes119-76-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes479-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1744-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes147-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes631-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1867-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1338-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes324-129-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes462-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1496-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes791-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes290-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes741-17-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1812-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes743-16-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1386-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes891-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes871-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1330-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes966-37-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1276-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1306-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes45-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1530-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1510-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes851-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes5-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1847-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes23-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1222-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1276-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes958-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1209-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1646-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes853-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes394-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/e0408020161109141820.wav.txt.v1-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1213-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1641-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1438-13-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1953-75-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1930-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1612-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1007-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes133-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1522-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1584-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1795-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1080-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1485-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1826-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes369-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-400-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-240-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes108-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1277-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes641-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1860-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1216-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes198-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1573-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1075-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1366-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes756-26-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1571-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-360-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1677-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1435-20-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1086-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1490-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1697-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1951-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1842-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes289-26-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1774-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-280-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes666-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1921-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1272-19-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1124-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1370-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1546-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes381-30-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes493-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes315-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes93-23-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1137-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes462-43-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes425-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1767-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1157-19-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes457-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1101-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes499-21-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes593-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes926-16-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1028-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1430-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes549-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1940-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes711-16-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes340-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes382-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes203-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes437-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes667-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes470-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-480-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes676-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes313-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1346-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes140-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1815-17-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes626-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes78-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1863-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1349-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1799-100-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1505-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes422-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes422-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes581-28-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1117-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes809-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-480-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1907-20-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1517-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1785-26-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-511-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1353-21-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes611-23-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes853-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes804-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1732-20-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1494-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1744-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1560-22-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1389-23-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1203-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes156-320-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes412-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-240-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1143-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1711-21-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes600-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes779-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes30-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1200-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1937-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1563-77-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1765-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes101-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes228-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes893-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes650-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1364-94-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes794-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1431-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes275-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1309-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes253-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1075-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1918-29-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1543-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1967-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes886-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes588-91-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1743-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-400-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes874-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1107-14-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-360-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1745-16-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-280-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes469-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes947-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes415-320-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes355-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-360-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes156-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1241-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1821-28-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1909-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1273-27-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes450-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes582-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes698-357-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1775-23-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1170-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes928-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes117-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes251-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1837-17-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1362-200-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes868-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1206-21-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1768-33-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1965-55-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1628-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1639-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes60-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1670-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes480-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1951-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1966-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1225-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes73-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1309-160-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1286-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1644-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-480-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes784-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1373-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1424-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes810-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes697-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes161-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes708-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes533-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1394-38-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1871-17-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes28-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1033-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1348-20-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1086-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes919-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1071-38-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1892-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes191-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1254-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1322-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes958-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1115-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1799-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes899-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes371-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes816-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes178-25-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1969-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1386-49-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes691-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes722-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes331-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes410-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1514-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes684-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1527-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes776-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes336-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes745-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1583-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes941-38-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1426-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes815-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1310-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes188-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes565-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes107-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes175-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1428-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1043-23-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes590-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1666-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1412-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes570-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes671-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1109-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes785-45-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1300-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes77-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes789-71-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1318-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1858-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1012-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes164-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1322-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1662-95-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1799-100-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes841-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes661-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1236-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1332-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1412-120-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes176-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes411-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes57-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes96-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-240-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes78-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1683-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes706-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1819-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes299-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes92-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes736-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes856-78-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes422-160-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1507-38-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1582-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes209-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-520-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1152-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1893-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1729-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1171-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1896-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1636-38-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1287-154-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes85-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1298-20-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes916-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1505-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes169-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes794-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1863-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1906-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes522-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes830-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1159-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1542-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-440-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes478-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes675-31-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes588-91-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1344-18-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1815-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes505-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes460-200-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1093-110-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes614-20-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1883-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1201-36-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1845-20-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1606-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes882-32-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1797-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes892-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes189-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes788-18-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes391-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1220-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes916-240-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-280-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes266-26-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes460-360-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1581-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1694-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1215-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1025-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes40-160-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes364-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1740-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes996-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1153-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes22-21-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes174-26-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes2-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1362-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1796-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes782-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes212-206-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1153-200-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes698-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-676-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1794-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1650-16-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes446-17-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1659-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes531-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes5-305-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1438-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1053-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1522-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1480-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1884-23-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1899-124-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1032-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1849-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1171-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-600-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes911-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1559-33-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes546-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1713-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes757-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1153-234-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1105-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1818-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes460-240-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes756-26-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes856-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes214-21-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes460-200-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes386-25-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes287-23-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1358-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1390-28-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes337-16-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1943-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1265-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes380-23-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1748-38-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-240-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes184-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes802-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1896-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-240-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes124-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes562-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes422-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes234-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes10-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1969-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1764-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1362-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1172-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-240-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1085-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes782-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes335-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1801-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes823-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1263-28-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1886-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes551-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1210-38-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1467-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes496-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1293-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-200-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes194-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1468-24-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1440-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes759-20-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes520-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1199-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes400-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1238-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1802-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1788-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes634-19-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1183-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes998-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1945-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1451-13-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1809-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes910-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1609-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes53-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes860-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes553-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1314-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1362-261-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1538-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1917-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes204-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-200-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes211-33-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes305-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes187-20-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1915-120-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes299-94-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1895-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1007-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes419-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes76-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1661-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes511-38-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-200-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes419-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes822-19-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1137-245-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes977-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1778-280-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes698-357-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1534-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1137-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes321-31-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes558-33-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes432-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes679-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes681-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1423-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1377-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1365-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1449-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1057-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1703-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes943-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1429-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1872-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-280-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes495-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes687-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1382-18-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1128-13-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes143-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1676-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1036-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes162-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1919-16-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes472-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes373-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes205-28-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes417-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1958-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes391-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes493-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes522-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1557-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1351-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes68-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1622-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1180-25-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes127-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes921-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes69-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes951-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1659-13-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1306-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-520-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1086-307-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes509-27-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1580-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes620-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes36-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1194-25-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1751-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1033-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1308-38-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes832-20-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1799-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes489-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes681-118-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1743-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes19-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes886-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes51-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes235-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1075-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1832-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1915-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1839-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes208-34-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes292-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes524-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes542-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-160-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes468-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1735-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes115-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1723-22-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1332-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1464-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1048-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes728-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1875-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1950-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1880-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes580-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1574-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-480-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes110-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes568-16-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes481-160-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes639-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes619-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1357-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1183-71-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-400-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes193-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes698-240-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1552-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes59-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes111-38-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes231-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes682-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes301-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes172-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1362-240-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-320-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1706-13-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes992-24-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1005-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes603-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes87-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes97-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1932-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1057-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes821-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes479-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes466-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes184-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1591-66-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1288-67-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes477-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1730-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes460-240-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1291-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1821-28-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes461-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1239-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes749-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1384-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1915-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes278-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes898-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes585-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes878-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-200-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-280-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes249-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes248-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes284-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1900-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1335-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1573-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes568-16-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1520-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes338-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes458-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes142-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes229-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes372-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes404-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes614-20-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1670-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1042-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1563-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1942-30-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1863-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1778-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes942-35-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1309-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1111-108-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1119-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes415-280-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/e1001420161109111112.wav.txt.v1-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes334-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes587-16-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes823-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1441-34-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1868-17-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes154-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1264-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1732-20-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-440-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes915-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1483-29-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes933-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1412-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes95-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes80-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes250-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes132-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1384-160-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes414-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes549-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1522-41-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes767-16-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1785-26-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1156-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-440-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes885-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1282-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes734-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1064-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1155-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1591-66-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1430-51-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes86-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes994-48-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes651-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1163-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1132-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes213-18-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1423-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes142-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1613-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes774-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes866-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1678-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes463-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes220-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1798-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1299-22-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes418-21-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes866-18-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1805-28-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes266-26-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1873-23-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1922-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1548-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-240-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1583-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1269-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes70-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1277-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes299-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1191-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes123-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1851-26-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1007-363-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes415-240-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes103-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes871-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1489-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1915-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes853-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes574-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1851-26-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1541-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1787-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes481-240-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1915-202-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1671-8-2 data/dmnYesHasInsTest
