#number of total: 11824
mv -i data/dmnYesHasInsTrain/genYes801-480-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1610-147-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes534-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1141-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes938-39-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1441-34-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes628-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes788-18-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1594-95-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes735-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1147-21-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes100-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes359-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes18-36-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes374-28-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes87-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1692-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes530-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes20-23-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1370-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes245-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes570-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1642-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1580-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes885-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes771-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes560-22-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1582-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes392-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes61-30-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1031-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1378-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-320-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1153-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1055-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes370-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes518-48-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes212-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes787-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1280-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1353-21-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes288-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes600-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1156-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1111-108-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes330-38-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1214-23-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1961-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1512-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-160-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1664-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1334-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes10-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes460-240-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1283-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1580-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1727-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-280-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1020-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1086-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes528-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes134-20-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes303-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes637-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1687-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1134-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes212-160-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1094-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1795-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes415-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1376-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes580-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes684-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1231-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1183-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes740-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes119-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1135-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1744-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1007-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes965-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1210-38-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-440-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1663-27-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1934-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes52-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1266-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes132-224-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes803-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1427-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1953-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes494-20-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1723-22-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes569-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes884-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1865-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes516-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1362-240-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1171-160-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes745-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes964-21-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1941-17-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes559-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-240-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1890-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes448-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes4-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1658-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes104-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes631-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes853-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes651-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes652-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1457-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1542-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes117-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1700-22-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes460-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes592-22-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1881-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1726-24-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes410-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1435-20-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1533-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes575-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes108-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1042-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes687-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes551-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1522-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes882-32-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1205-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes683-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes110-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes648-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes880-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes824-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1232-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes340-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1427-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1012-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1255-13-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1795-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes247-53-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1470-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1801-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1320-16-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1671-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes779-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes394-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1722-17-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes683-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1507-38-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1576-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes978-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes916-306-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1743-129-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1714-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1564-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes447-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes909-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1863-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1662-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes879-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1734-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes358-20-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1014-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1328-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes156-160-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes19-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes512-17-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes681-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes239-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes229-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1360-24-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1283-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes529-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1153-200-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1572-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1239-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1926-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes388-19-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes973-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1697-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes13-53-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1896-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes341-39-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1953-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes257-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes973-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1623-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1291-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes983-38-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes456-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes894-200-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1810-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes424-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes932-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes422-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes338-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1482-22-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1871-17-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1269-13-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes249-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes205-28-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes241-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1580-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1439-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1688-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes235-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes441-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes225-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1111-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes509-27-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes54-22-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes138-16-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1309-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1828-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes894-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes409-20-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes468-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes902-268-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1287-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1406-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1620-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes602-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1872-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1908-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1368-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1789-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes811-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes715-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1793-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1399-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes953-13-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes649-120-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1619-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1952-17-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1093-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes766-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes186-38-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1969-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1795-134-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1818-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes996-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1719-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes582-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes606-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1317-26-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1187-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1573-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1364-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes393-32-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes74-24-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes235-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes667-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes605-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1111-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1437-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1386-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes670-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1838-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes359-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1309-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes226-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1799-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes38-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1795-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes276-21-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes849-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes784-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes50-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes865-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes275-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1884-23-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes553-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes72-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes828-20-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1086-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1667-16-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1391-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes111-38-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes406-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1875-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1223-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1298-20-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes51-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1593-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes800-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1362-261-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1542-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes891-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1617-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-280-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes627-161-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1938-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes243-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1100-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1182-23-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1850-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1476-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-404-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1518-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes503-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-400-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes415-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1558-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1111-108-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-240-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1178-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes16-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1485-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1580-193-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1423-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1259-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1780-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes582-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1858-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1405-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes607-19-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes994-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes652-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1910-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes743-16-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes587-16-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1055-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1750-29-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes406-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes950-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes979-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1779-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes966-37-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1848-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1360-24-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1306-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1748-38-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes516-178-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes830-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes509-27-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1522-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes647-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1515-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes287-23-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes459-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1722-17-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes758-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes444-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1333-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1539-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes710-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes465-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1052-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes929-24-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes245-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes55-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes269-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes688-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes415-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1081-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes78-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes10-107-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1915-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1845-20-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1828-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1352-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1617-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes449-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1808-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes289-26-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes10-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes843-27-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes846-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1814-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1588-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1272-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes49-16-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1304-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1534-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1551-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1336-23-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1194-25-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes900-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1841-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/20150128172328_1117_13665858885_55076.wav.txt data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes130-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1861-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes154-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1029-26-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1591-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1554-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes157-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes142-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1564-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes909-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1522-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes788-18-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes953-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1146-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes105-29-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes850-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1072-38-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes385-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes950-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1648-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1604-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1899-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes92-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1362-160-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes657-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes290-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1079-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1800-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1518-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes78-90-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes403-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1774-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes21-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes588-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes555-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1819-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1318-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes784-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes861-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes851-65-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1513-19-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1888-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes54-22-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes534-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes918-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1965-55-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes5-240-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1187-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1366-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes77-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes181-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes369-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes105-29-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1086-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes764-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes281-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1347-35-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1805-28-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1093-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1420-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes261-16-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1676-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-200-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-320-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1895-76-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1436-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes891-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes779-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes346-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1323-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1891-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1622-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1534-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1555-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1065-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1710-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1163-14-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes674-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes860-96-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes692-20-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes560-22-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1176-28-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1044-21-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes334-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1775-23-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes23-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes820-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes212-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1766-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes671-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1596-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1081-18-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1036-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1171-221-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1349-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1938-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1752-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-240-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1377-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes743-16-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes113-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes144-23-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes65-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1953-75-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1316-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1239-17-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes626-12-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes823-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes610-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1094-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes417-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes210-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1829-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1269-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes415-364-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes609-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1919-16-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1018-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1067-12-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1330-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1203-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes247-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes178-25-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1079-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes691-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-323-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1359-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1447-53-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1633-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes328-41-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes77-49-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1097-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1533-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes489-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1242-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes518-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1171-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes555-19-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes515-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes93-23-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-200-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1581-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1600-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes756-26-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes337-16-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-640-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1514-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1563-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes757-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1412-128-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1048-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes263-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes345-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1260-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes395-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1768-33-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1673-16-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1938-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1912-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes323-16-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1588-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1150-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1695-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1437-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes446-17-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1221-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes504-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1594-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1384-200-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1178-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes70-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes955-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes831-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1419-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1505-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes217-26-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1061-38-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes120-26-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes324-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1400-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1519-21-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-240-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1751-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1534-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes909-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1563-77-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes348-21-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1095-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1245-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1179-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1664-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes15-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1417-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-200-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1352-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1833-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes935-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1835-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1091-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes278-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1967-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes880-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1626-24-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes820-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1860-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes156-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1363-13-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes63-16-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes803-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes244-16-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1069-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes299-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1200-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1832-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes414-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1779-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes139-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes842-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes169-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes892-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1808-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-600-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1106-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1203-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes896-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes118-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1128-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes532-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1585-18-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes880-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes627-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1433-23-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes677-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1379-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1135-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1366-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes347-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes644-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1797-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes523-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes101-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1922-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1068-38-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1906-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1054-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1933-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1785-26-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1770-18-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes405-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1106-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes402-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes922-21-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1471-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes860-96-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes853-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes548-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-280-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1507-38-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes828-20-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes7-22-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes132-200-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1577-17-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1575-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1267-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1469-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1265-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1318-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes813-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes737-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes7-22-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes965-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1341-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes457-19-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-240-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1788-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes537-16-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-200-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1293-55-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes894-308-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes627-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes241-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1799-100-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1111-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1854-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1034-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes744-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes272-25-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1344-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1422-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes247-53-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1790-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1899-124-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes315-197-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes911-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1676-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes123-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1386-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1214-23-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1264-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1445-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1375-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes698-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes410-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes78-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1153-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1494-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes26-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1379-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1057-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes688-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes66-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1844-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1812-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1580-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1359-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1915-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1883-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes713-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1414-29-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes807-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes183-78-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1430-51-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1460-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1473-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes993-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1632-22-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes771-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes859-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1598-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes417-43-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes143-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes33-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1071-38-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes635-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1934-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes55-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1164-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1955-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes505-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1339-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-320-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1696-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes77-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes502-36-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1051-38-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes770-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1793-100-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1819-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes198-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes978-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1852-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes117-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1417-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1967-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes728-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes818-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1724-54-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-511-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes905-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes485-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes53-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes416-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1419-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1743-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1467-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes725-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1944-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes432-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes75-20-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-440-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes870-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-520-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes463-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes848-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1052-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1321-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes546-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes903-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes397-14-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes471-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-284-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1284-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes641-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1558-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes59-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes677-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1620-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1872-19-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1115-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes413-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1936-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1810-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1928-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes660-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1930-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes798-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1959-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes152-19-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1113-18-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1166-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1342-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes491-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1958-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-360-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1713-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1799-100-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes894-200-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes906-16-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes153-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes916-200-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes865-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-240-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1029-26-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-539-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes839-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1025-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1487-38-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes89-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1183-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes681-118-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes466-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1519-21-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1606-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1030-16-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1294-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes286-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes43-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes67-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes101-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1546-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes546-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1257-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes853-180-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes642-30-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes698-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-320-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes689-23-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes340-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1365-46-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1778-240-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes204-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1558-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-323-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1646-93-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1604-160-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1323-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1696-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes799-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-400-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes99-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes422-240-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes659-22-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-361-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes393-32-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1925-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes174-26-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes991-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1811-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes399-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1459-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1332-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1610-147-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1640-30-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes451-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes299-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1712-29-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1259-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1887-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1626-24-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1789-38-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1057-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1028-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes397-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1358-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1657-18-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes5-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1095-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes861-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1774-187-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1348-20-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes637-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes162-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes132-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-320-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1073-26-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes472-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1149-26-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1007-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes356-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1216-13-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1142-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes427-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1408-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes5-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes936-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1584-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1778-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes338-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1656-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes916-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1105-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1697-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes268-24-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-640-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes781-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes209-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes500-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes376-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes178-25-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes888-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes997-23-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes887-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes338-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes749-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes187-20-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes319-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1185-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes354-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes719-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1742-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-280-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes434-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1071-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes530-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes737-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1609-38-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes443-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes726-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1666-18-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1222-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1416-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes768-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes549-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes617-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes550-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1099-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes82-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes833-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1524-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1130-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes480-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes965-176-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes538-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-404-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1616-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1833-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes779-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes196-22-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes417-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1119-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1639-79-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1265-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes250-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes471-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1724-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes201-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes644-133-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes415-320-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1574-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1875-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes324-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes332-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes714-16-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes687-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes853-180-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1137-245-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes516-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes253-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes488-20-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes745-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1629-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1309-191-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes91-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes109-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes417-43-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1087-35-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes566-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes500-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1091-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes26-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes67-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1580-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1591-66-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes723-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1858-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes680-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1007-280-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1797-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1688-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes417-43-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes393-32-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1534-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1563-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1770-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes137-22-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes881-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes849-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1425-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes324-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes619-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes895-26-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes162-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1014-82-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1198-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1325-27-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes325-38-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes789-71-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-640-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes641-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes873-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-440-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1924-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes222-63-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1751-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes103-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes856-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1553-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes181-19-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes156-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1208-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes894-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1122-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1048-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1541-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes212-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1011-16-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1214-23-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1948-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes578-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes902-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1084-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1431-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1330-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1965-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes56-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1925-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1555-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes422-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1285-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1375-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1309-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes806-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1014-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes78-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-520-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes806-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-320-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1134-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1778-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1008-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes509-27-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1001-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1137-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1935-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes440-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1279-37-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1016-81-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes124-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1066-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-280-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes389-16-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1493-27-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes595-28-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes803-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes787-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1615-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1454-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes907-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes738-28-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes21-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1238-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-400-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1328-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1915-200-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes781-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes905-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes17-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1098-17-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1778-280-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes649-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes356-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1778-120-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes219-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes329-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes649-219-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1831-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes570-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1169-37-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes526-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1178-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-410-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-511-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes236-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1509-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes491-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1308-38-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes727-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes761-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1564-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes704-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes698-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1637-13-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1815-17-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1731-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes517-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1340-22-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1202-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes662-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes826-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes69-64-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes109-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes762-31-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes807-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1765-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-240-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1465-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1876-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes898-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes67-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes134-20-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes627-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes478-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes867-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1943-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-360-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes231-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes460-200-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1621-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1434-22-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1787-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1081-18-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes809-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes968-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes716-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes796-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1093-110-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes94-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes588-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes549-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes41-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes190-23-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes311-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes906-16-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes422-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-120-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-240-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1877-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes660-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes426-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1485-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-560-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes482-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes541-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes406-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes698-200-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1791-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-480-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1232-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1330-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1720-18-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1312-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1040-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1431-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes770-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1379-45-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1334-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes700-16-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1911-21-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1328-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes589-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes803-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes566-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1372-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes132-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1542-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes889-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes220-4-3 data/dmnYesHasInsTest
