#number of total: 11866
mv -i data/dmnYesHasInsTrain/genYes1915-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes460-440-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-320-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes796-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-160-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes106-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1143-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1924-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes865-19-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes212-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1690-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1891-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes860-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1598-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes859-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1933-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1588-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes994-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes160-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1557-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1288-67-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1287-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes260-26-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes312-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes370-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes916-280-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes642-30-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1132-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1898-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes814-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1209-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes103-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1243-16-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1936-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1321-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes498-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1426-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1659-13-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1254-17-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes141-13-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes634-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes934-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes930-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes610-12-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1234-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1534-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes40-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1699-32-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes708-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes894-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes782-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes601-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1430-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1591-66-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1911-21-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1111-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1682-25-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1644-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes596-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1007-320-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1669-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes883-20-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes558-33-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes371-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes5-305-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes765-23-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes307-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes539-30-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes626-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1864-20-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes460-320-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1233-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1385-29-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes828-20-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1735-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes930-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes460-240-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes400-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1287-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes874-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes849-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1601-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1688-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-200-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1502-38-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-200-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes929-24-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes151-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes671-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1882-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes843-27-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes63-16-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes552-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes969-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1471-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes493-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-120-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes687-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes217-26-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1902-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes873-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes212-206-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1751-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1309-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1606-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1417-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes737-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes395-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes374-28-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes114-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes79-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes803-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1253-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1736-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1356-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-200-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes300-23-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes156-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes528-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes87-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes302-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes452-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1187-200-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1916-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes641-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1559-33-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes205-28-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1105-120-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1308-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes55-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1337-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes739-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1893-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1740-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes627-161-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1631-19-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes566-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1538-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1183-71-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1307-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1745-16-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1774-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes816-54-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1956-22-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes485-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1111-108-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1494-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes955-13-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes568-16-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes995-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes853-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1128-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1806-29-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes837-37-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1737-16-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes169-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1333-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes961-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1795-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1661-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes493-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes759-20-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes445-29-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes560-22-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-440-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes117-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes898-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-400-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1831-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1093-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes81-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes5-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1842-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1535-30-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-280-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1371-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1233-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1585-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes831-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes24-18-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1099-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes429-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes926-16-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes404-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes456-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1192-12-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1819-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1606-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes299-94-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes990-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1445-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1347-35-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1517-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes285-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1792-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes345-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1508-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1725-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1275-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes844-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes208-34-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1491-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes734-19-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes494-20-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes299-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes838-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1089-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1181-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes559-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1281-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1899-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes627-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1698-28-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1354-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes190-23-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1366-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1899-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1839-68-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1534-186-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1905-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes757-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1907-20-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes996-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1817-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes315-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes739-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1386-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1063-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1086-307-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1221-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1580-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1429-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1886-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1221-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes618-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes125-18-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1031-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes184-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes431-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1542-149-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1423-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1033-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes866-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes811-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes414-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes843-27-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes119-76-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes484-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes983-38-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes719-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1364-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes741-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes943-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes785-45-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes996-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes834-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1098-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes23-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes207-29-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1646-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes465-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes740-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes385-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1064-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1750-29-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-480-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1051-38-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes712-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes922-21-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1362-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes741-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes470-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1677-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes170-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1069-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1805-28-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1461-29-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes916-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes333-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes965-120-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1288-67-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1543-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes134-20-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1965-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-240-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1455-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1483-29-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes294-59-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes812-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1141-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes96-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1014-82-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes715-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes415-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes260-26-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes315-120-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes43-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes784-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes777-17-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes668-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1900-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes93-23-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1460-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes468-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes325-38-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes760-23-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1485-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1409-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes681-118-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1137-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes826-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1448-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1273-27-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes2-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes964-21-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1811-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-200-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1530-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1748-38-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes666-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes882-32-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1003-20-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1259-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1212-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes203-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes535-22-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1370-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes69-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1373-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1755-22-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes611-23-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-400-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes860-96-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1827-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1302-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes996-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-480-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1577-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes748-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1174-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes302-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1552-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1922-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes821-38-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes954-30-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1778-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1563-77-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes387-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes433-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes869-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes738-28-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1774-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes711-16-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1603-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1677-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes796-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1157-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1216-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes974-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes784-174-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes214-21-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1171-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes547-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes477-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1638-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1962-16-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1204-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes894-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1927-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes643-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes175-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1319-23-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes283-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes662-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes857-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes938-39-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1538-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1701-30-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1118-13-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1536-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1899-120-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1131-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes148-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1398-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes240-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1665-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1326-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1078-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1311-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1411-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes298-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes324-129-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes486-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1889-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1041-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes965-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes830-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes926-16-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes916-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes78-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes901-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes986-38-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes58-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1776-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1341-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes448-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1493-27-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1443-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes641-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1001-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes256-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes212-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1598-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-280-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1778-303-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes349-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1142-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes390-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes305-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes222-63-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes601-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes686-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes445-29-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1777-20-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes458-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1865-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1750-29-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes881-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1223-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes644-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes550-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes736-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes84-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1199-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1039-24-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1348-20-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1430-51-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1480-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes592-22-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1338-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes776-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes584-25-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes725-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1121-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1575-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes644-120-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes593-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1412-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1115-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1908-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1149-26-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes878-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes697-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1400-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes627-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes405-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes885-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes503-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1081-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1780-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes437-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes503-18-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-280-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes862-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1472-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1899-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1915-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1128-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1869-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes897-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1223-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes228-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes512-17-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1520-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes518-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes677-12-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes604-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1410-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes163-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes355-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes518-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1430-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1912-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1137-200-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1211-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes156-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes11-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes352-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1450-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes993-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1634-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes107-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes952-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes797-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes170-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes126-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes481-240-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-400-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes67-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes836-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes40-179-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1577-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1911-21-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes506-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1874-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1293-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes8-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1165-17-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1404-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1014-82-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes299-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes303-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1228-18-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1362-261-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes738-28-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1909-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes845-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1085-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1329-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-240-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes307-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes374-28-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1034-14-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes808-24-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1288-67-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1738-33-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes225-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1111-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes223-2-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes190-23-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1618-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes239-14-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1924-18-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1965-55-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes555-19-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1958-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes15-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes597-38-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1036-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes838-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1277-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1680-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes197-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1675-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes21-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1628-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1081-18-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes821-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes967-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes556-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes31-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes476-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes490-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes389-16-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1580-193-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes202-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes271-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1265-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1787-41-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes714-16-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes688-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes554-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1882-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1288-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes580-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes949-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes960-12-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes35-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-520-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes954-30-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes913-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes739-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes812-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1380-22-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1514-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes212-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1418-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes851-65-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1183-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes906-16-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes211-33-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes224-20-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1221-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes595-28-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes204-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1810-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1489-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1765-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes460-440-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1410-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1534-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes978-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes99-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1718-16-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1932-14-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes487-38-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1862-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes353-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes635-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1769-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1168-12-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-400-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes561-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1118-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1716-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes444-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes12-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1403-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes415-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1301-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1931-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-280-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1897-23-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/e1005220161109162258.wav.txt.v1-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes795-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1539-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes723-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1046-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1362-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1185-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes215-18-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes582-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes804-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1287-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1637-13-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes766-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1191-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes517-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1300-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes791-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes897-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes777-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1288-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes951-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes965-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1007-200-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1039-24-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes722-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes130-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes568-16-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes807-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes902-200-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes37-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes905-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1458-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes894-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1637-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1862-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes315-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1414-29-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1471-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes790-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1575-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1534-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1083-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes46-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes659-22-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1370-87-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes641-160-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1795-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1550-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes649-219-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1132-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1453-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes520-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1423-154-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1007-360-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes335-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1274-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1805-28-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1900-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes109-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes542-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1805-28-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes281-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1365-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes421-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1239-17-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes572-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes598-13-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1783-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-160-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes204-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1305-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1845-20-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes995-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes858-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1458-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1713-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes57-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes916-280-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes844-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1167-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1580-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1799-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1057-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes534-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes116-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes649-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1639-79-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes686-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1802-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1362-200-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1428-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes531-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-320-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes145-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-280-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1913-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1925-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1383-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes876-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1953-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1666-18-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1138-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1134-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1457-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes944-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1780-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes212-200-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes620-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes234-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1294-19-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1939-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1245-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1546-14-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes649-200-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes10-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1379-45-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1950-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes507-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1599-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes649-219-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes394-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1486-30-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes474-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes725-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-160-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1441-34-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes666-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1787-41-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1915-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1474-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes823-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes610-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1072-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-280-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes208-34-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1604-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes968-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes312-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes856-40-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1309-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes188-117-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1268-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes212-200-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes805-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes512-17-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes389-16-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes734-19-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1356-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/20150330192009_659_18367562966_53159.wav.txt data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes771-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes902-240-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1617-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1732-20-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes412-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1406-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1187-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes391-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1951-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1196-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes344-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes66-19-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes698-200-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes885-13-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1445-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes387-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1339-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes562-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1108-19-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1695-12-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes56-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes261-16-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1713-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1844-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1788-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1508-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1137-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-410-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1158-17-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1202-11-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1018-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes447-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1491-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1199-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1086-280-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1060-27-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1169-37-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1608-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1831-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes724-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1272-19-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes387-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1590-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1811-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1423-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes641-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1573-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1299-22-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1243-16-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1035-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1755-22-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes586-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes577-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1187-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1571-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1044-21-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes133-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1364-94-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes289-26-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes295-16-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes119-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes962-17-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1172-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes709-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1115-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1384-200-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes812-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes192-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1137-200-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes543-21-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes17-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1628-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes860-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes120-26-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1812-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1309-80-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-200-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1711-21-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes301-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1276-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes778-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1854-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1441-34-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1479-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes582-13-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes156-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1297-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes288-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1047-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1476-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1379-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes290-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-648-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1309-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes579-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes502-36-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes497-27-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes829-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes852-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes956-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes917-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes531-4-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes446-17-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1944-9-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1654-5-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes885-13-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1045-21-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes871-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes624-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1794-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1829-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1109-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-360-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes524-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1120-22-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes218-38-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1784-13-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1307-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes244-16-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes625-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes5-200-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1530-9-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1686-13-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes644-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1772-34-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes215-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes415-280-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1822-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1586-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes9-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1607-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1452-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1616-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes758-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1521-16-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes279-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes145-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes593-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-560-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes346-17-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1473-14-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1287-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1479-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes204-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes422-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1791-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes613-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes619-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes986-38-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes408-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1438-13-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes139-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes528-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1760-38-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1145-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes983-38-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes226-12-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes894-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes784-120-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1580-193-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1399-18-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-480-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes285-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1325-27-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes67-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes645-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1790-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1396-32-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes330-38-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1154-16-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes388-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1123-15-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1915-160-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes422-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1946-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes847-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1743-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1724-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes422-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1682-25-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes615-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1720-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1589-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1432-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1459-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes194-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-640-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1828-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1632-22-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1866-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes912-10-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1223-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1423-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1141-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes321-31-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes950-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1729-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes578-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes5-120-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes471-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1160-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1610-147-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1516-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes401-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes751-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1506-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes69-64-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1682-25-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1008-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes698-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1489-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1461-29-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes191-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1450-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1201-36-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes66-19-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1408-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1754-22-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes264-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1946-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1240-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes311-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1177-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1496-40-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1428-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes860-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1826-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes450-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-80-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1893-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1050-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes307-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes432-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1217-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1392-24-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1927-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes255-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes426-13-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes801-320-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes295-16-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes683-4-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes172-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes460-400-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes718-6-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes222-63-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1362-200-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-360-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1122-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes133-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes629-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-480-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes654-38-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes269-10-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1447-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1031-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes104-11-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes132-200-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1759-320-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes726-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-400-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes709-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1388-18-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1836-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1258-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes607-19-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1215-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1279-37-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes450-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes594-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-480-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-440-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes38-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes119-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes198-62-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1339-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1595-15-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes861-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1868-17-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes204-14-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes675-31-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1140-17-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes67-193-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1063-9-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1840-17-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1276-12-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1340-22-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1313-320-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes942-35-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1369-20-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-40-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes791-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1583-11-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes464-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes40-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1799-100-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes562-3-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes228-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1104-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes517-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-361-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes429-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1862-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1376-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes592-22-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes588-80-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes916-306-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1794-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes329-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes103-6-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes435-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1575-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes101-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes478-5-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes334-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1658-3-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes424-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes44-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes844-7-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes368-17-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1765-18-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1820-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1493-27-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes802-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1271-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1009-6-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes402-7-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1715-17-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes983-38-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes586-8-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1315-3-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1055-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1710-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes669-3-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes929-24-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes996-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-676-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1256-400-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1414-29-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes389-16-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes678-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes843-27-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes118-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes658-10-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1292-14-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1260-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1392-24-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes755-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes156-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes900-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes873-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1855-200-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1583-11-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1440-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes280-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1666-18-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes211-33-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes894-280-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes293-320-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes853-120-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1681-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1417-7-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1020-5-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1436-8-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1080-7-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes219-8-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes688-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes57-4-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1183-40-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes902-240-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes638-12-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1326-7-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes559-8-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes839-5-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1926-9-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-360-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1771-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes5-40-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1572-5-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes415-364-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1723-22-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1888-11-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes942-35-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes156-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1540-80-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes223-2-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes579-6-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1022-360-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1137-160-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1920-80-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes702-29-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1931-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1387-9-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes527-120-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes138-16-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1373-15-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes992-24-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes647-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1351-18-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1147-21-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes3-8-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1972-15-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes653-10-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes598-13-2 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes909-4-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes209-4-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1019-10-3 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1010-3-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1384-120-4 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes339-6-1 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes684-15-0 data/dmnYesHasInsTest
mv -i data/dmnYesHasInsTrain/genYes1708-38-2 data/dmnYesHasInsTest
