#number of total: 10781
mv -i data/dmnYesHasInsTrain/genYes522-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes834-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1086-120-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1658-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1948-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1159-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes595-28-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1397-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes524-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes641-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-200-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1650-16-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1924-18-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1534-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes574-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes817-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1597-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes277-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes256-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1747-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1017-19-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes975-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes525-17-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes662-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes808-24-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1396-32-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes924-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1312-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes67-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes879-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1362-120-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-320-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes307-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes40-179-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes575-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1214-23-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1709-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1222-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes138-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes649-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1778-200-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes564-32-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes543-21-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1914-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes117-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes644-120-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes900-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes698-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes3-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes644-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1688-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes40-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1965-55-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1224-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes432-94-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes985-26-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1688-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1851-26-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1047-320-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1197-24-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes5-200-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1607-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1826-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes256-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1331-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes888-17-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes930-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1049-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes838-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes969-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-160-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes902-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes727-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes442-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1148-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1608-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1855-120-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1452-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes661-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes939-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1312-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes800-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1910-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes993-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1234-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1081-18-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes995-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes725-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1903-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1292-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1632-22-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1709-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes928-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes106-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes526-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1326-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1067-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes569-15-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1510-38-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes812-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes145-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes92-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1555-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1473-14-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes188-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes463-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes938-39-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1607-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1925-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes571-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes319-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes916-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1145-120-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1093-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1781-33-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1642-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-200-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1768-33-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes894-200-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes381-30-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1674-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes385-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-320-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1641-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes837-37-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes363-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1002-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1052-93-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes159-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes405-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes305-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/E0502420161109143622.wav.txt.v1-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1685-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-320-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1889-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes334-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1738-33-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-320-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes421-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes38-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-160-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes683-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1355-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-160-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes718-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes981-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1212-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes968-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1086-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes304-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1032-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes461-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes817-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1361-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-240-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes365-11-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes555-19-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes641-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes61-30-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1057-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1053-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1937-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes649-219-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-676-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1065-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1442-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1368-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1161-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1111-108-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1371-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes176-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes330-38-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1174-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes86-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes941-38-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes356-19-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes375-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1182-23-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1430-51-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-240-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1352-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1880-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1953-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1495-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes197-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes320-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes526-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes171-67-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes252-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes493-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-480-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes0-24-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes678-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes348-21-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes119-76-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes756-26-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1107-14-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1828-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1086-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1071-38-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1240-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes327-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-360-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1805-28-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes607-19-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1913-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes77-49-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes403-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes890-43-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes817-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes514-15-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1247-2-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes408-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes115-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1126-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes595-28-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-480-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1223-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes131-19-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1086-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1411-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1152-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1405-13-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes464-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes268-24-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1292-14-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes831-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes167-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1676-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes212-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes640-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-360-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes476-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1199-120-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes117-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes200-23-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes902-240-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-280-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1621-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes415-280-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1954-58-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-360-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes983-38-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1662-95-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes671-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes970-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes313-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes873-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1496-66-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes578-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1887-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1851-26-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes132-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes27-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes326-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1555-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1673-16-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1698-28-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes530-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes836-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1795-134-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1187-210-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes61-30-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1059-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1724-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes156-320-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes949-41-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes350-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1014-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes694-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes780-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1720-18-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes442-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes244-16-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes824-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1419-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1774-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1599-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1249-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1532-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes858-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes541-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1450-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes903-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1733-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes760-23-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes489-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes219-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes952-12-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1318-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes739-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes488-20-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes181-19-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1093-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes383-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes68-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1026-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes629-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1910-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1255-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes84-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes265-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1094-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes51-12-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1047-324-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes558-33-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes415-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes247-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1865-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes604-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes468-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes537-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1634-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1853-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1426-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1104-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1304-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes120-26-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes94-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes930-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1796-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes258-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1578-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes991-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1042-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1582-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes772-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1088-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes516-178-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes78-90-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes102-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-320-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1878-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1245-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1790-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes409-20-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes276-21-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes13-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1000-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1171-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1030-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes784-160-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1816-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes971-21-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1925-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes847-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1828-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1895-76-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes977-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes925-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes636-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-511-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes665-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1092-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1169-37-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1656-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes178-25-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1604-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1741-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1856-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes649-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1627-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes627-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes156-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes907-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes542-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1823-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes753-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1423-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1358-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1362-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1184-36-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1342-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes231-141-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes160-13-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes696-22-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1950-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1566-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1743-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes405-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes864-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes945-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1499-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes116-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1049-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1828-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes264-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes189-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1620-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1520-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1286-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1540-280-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes315-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1204-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes935-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1285-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes691-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1934-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes881-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1252-37-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes259-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes56-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1319-23-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes926-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes775-25-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1774-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes278-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1787-41-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1778-303-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1580-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes787-13-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes152-19-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1079-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1372-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes728-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1719-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes212-200-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1176-28-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1145-125-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1250-23-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1742-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes299-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes197-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-280-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes544-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes325-38-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes695-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1527-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes481-120-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes676-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes914-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes159-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1168-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1264-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes763-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1827-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1631-19-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes449-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1318-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1646-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes350-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1633-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes902-240-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes315-197-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes185-34-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1542-149-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1423-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes350-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes67-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes503-18-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes602-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes28-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes232-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes570-198-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes108-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1052-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes127-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes229-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1368-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1779-12-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes6-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes142-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes136-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1255-13-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1400-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-400-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1827-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/20150303105648_1233_15024452011_55179.wav.txt data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes459-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1515-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1965-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1575-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes487-38-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1398-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1289-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1856-12-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes582-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1400-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes593-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes462-43-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes699-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-360-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes997-23-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1941-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1827-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes988-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes297-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-320-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1741-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes26-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes240-12-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1713-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-240-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes29-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes242-21-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1662-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1971-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes329-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1696-14-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1854-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1825-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes630-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1800-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes999-11-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes481-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1642-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes553-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1774-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1947-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes629-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes212-206-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1288-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1885-33-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1608-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1604-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes991-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1548-12-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1874-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes75-20-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes253-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes715-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes198-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes565-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1797-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes550-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes352-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes994-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1287-120-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1911-21-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes133-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes570-198-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1041-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1457-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes537-16-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1391-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes579-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1386-49-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes456-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes741-17-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes824-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1542-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes120-26-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes982-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes40-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes105-29-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes554-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes119-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1742-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes711-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1215-64-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1274-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1011-16-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes307-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes332-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes328-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1399-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1863-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes281-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1817-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes871-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes430-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1436-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1036-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1047-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes14-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes894-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes731-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes481-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1145-125-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1184-36-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes362-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1940-17-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-200-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1018-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes938-39-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1823-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes741-17-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes919-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1639-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes448-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1199-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1386-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes371-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1108-19-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes865-19-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes684-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes140-18-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes499-21-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes866-18-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes433-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes947-13-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-200-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1048-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes52-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1624-25-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1478-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1588-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1903-11-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes808-24-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1839-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes562-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes644-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1487-38-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1409-12-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes77-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes740-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1768-33-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1945-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-360-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1765-18-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1271-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes138-16-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes117-120-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes861-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1352-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes815-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1824-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1774-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes481-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1864-20-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes949-41-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1735-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-200-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1577-17-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-200-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1600-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes376-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes88-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes599-20-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1548-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1819-90-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes458-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-280-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes130-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes147-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1287-120-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1339-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes218-38-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes158-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1874-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1329-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1292-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes415-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes996-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1244-13-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes291-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes992-24-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes117-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes208-34-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes829-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes973-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes2-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes668-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1387-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1171-160-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1774-120-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1809-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes895-26-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes485-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1661-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1116-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1833-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1362-160-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1297-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1267-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1131-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes67-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes674-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes2-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1230-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes894-308-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1334-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1073-26-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1384-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes769-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes373-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes651-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes315-120-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes55-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes944-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1849-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes136-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes266-26-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1582-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1615-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes209-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-280-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes271-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1757-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes675-31-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1495-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1819-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1513-19-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-280-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes7-22-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes280-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1888-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes237-17-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1773-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1540-120-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1609-38-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1199-240-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes966-37-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes423-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes20-23-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes720-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes254-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-200-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1857-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes659-22-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes486-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes243-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1337-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1599-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1366-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1053-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes588-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes40-179-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes285-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes626-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes516-160-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes315-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1195-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1948-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1009-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes161-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes517-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1692-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1629-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes929-24-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1295-17-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes156-240-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1108-19-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1797-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes890-43-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes200-23-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1429-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1003-20-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes615-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes848-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes83-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes554-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1778-200-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes616-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes223-2-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1130-13-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes218-38-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes882-32-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes21-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1942-30-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes515-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1002-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1118-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1461-29-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes438-19-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes422-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1614-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1120-22-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes422-240-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes361-23-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes769-15-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1364-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1372-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1716-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1507-38-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes698-160-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes676-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-320-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1589-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1299-22-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes957-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1961-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes702-29-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1915-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1309-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1045-21-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1828-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1423-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes868-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes677-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes295-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1412-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes767-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes687-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1535-30-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes470-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1287-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes716-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-560-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1456-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1312-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1455-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1952-17-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes835-12-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes649-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes10-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes99-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes848-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1040-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes422-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1801-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1342-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1186-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1778-200-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes74-24-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes677-12-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes833-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1534-160-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1383-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1894-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes416-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1453-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes300-23-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes952-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes252-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes641-200-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1065-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1591-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1574-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes299-94-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1522-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1684-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1681-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1844-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes757-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes420-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1082-13-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1288-67-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1906-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes712-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-120-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1017-19-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes341-39-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1084-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes922-21-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1835-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1316-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1039-24-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1835-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1898-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1186-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes523-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes498-17-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1580-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes343-11-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes232-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1035-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1417-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes903-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1864-20-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes114-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1309-191-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes907-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1825-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes10-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-360-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1202-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1264-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-400-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1778-240-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1357-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1703-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1580-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes480-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes132-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-320-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1496-66-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1954-58-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes842-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes833-15-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes769-15-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1023-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes819-12-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes398-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes777-17-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1127-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1335-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes972-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes165-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1730-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes85-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1065-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1362-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1253-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes532-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes905-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1199-240-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1287-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1011-16-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes800-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1079-11-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes998-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1639-79-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes150-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1582-15-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-200-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-560-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes916-306-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1129-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes886-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1100-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes653-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes853-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1686-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1187-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1293-55-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1295-17-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes820-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-240-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1864-20-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes146-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1152-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1870-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1834-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1352-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes839-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes506-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1086-200-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1841-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes144-23-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1112-38-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1161-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1042-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes706-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes491-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1365-46-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes417-43-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes91-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1197-24-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1650-16-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1089-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes279-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes195-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1387-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1444-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes857-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1089-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1915-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes790-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes102-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes765-23-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes419-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes262-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes887-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes994-48-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1187-210-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1970-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1500-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes739-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1052-93-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1192-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes621-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes960-12-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1099-19-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes761-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes145-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1876-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1401-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes650-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes601-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1702-24-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1439-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes235-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes586-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1349-17-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes516-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1684-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1129-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes784-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1091-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1097-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1121-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1694-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes202-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1813-17-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1307-11-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes624-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1137-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes455-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes50-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1135-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes719-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1310-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-648-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes621-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1283-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1024-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes712-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1855-280-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1565-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes974-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-280-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes625-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes681-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1185-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1246-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes261-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes902-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1447-53-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1048-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1047-324-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1189-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1761-17-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes408-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-160-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1936-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1583-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes905-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1335-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes95-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1737-16-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1646-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1014-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes29-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-360-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1933-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1346-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes51-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes195-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-160-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1333-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1560-22-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1436-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1942-30-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes441-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes50-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes552-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes555-19-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes196-22-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1523-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes605-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1778-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1244-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1420-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes567-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes810-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes864-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1898-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1412-128-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1732-20-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes654-38-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes733-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1462-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1401-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes410-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes830-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1593-38-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1384-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes571-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1291-14-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1396-32-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes447-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1472-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes417-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1852-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1178-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes584-25-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes122-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1047-280-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes639-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1403-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes890-40-4 data/dmnYesHasInsEval
