#number of total: 10641
mv -i data/dmnYesHasInsTrain/genYes514-15-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes150-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes237-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes666-18-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1199-160-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes524-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes555-19-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes445-29-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes851-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes114-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes5-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1838-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes311-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes481-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes367-24-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes405-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1580-193-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes130-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1567-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes321-31-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1196-18-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes972-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1650-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1793-100-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes374-28-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes783-25-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes128-21-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes834-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes432-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes997-23-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1477-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes77-49-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1475-25-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1637-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes262-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes349-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes290-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1048-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1186-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1200-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes984-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1493-27-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1512-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1378-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1705-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes855-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes454-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes863-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes759-20-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1177-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes846-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes115-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-648-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1625-12-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes317-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1882-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-560-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes868-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1536-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes605-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes40-179-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes145-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes533-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes405-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1961-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1825-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes764-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes16-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1886-12-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes677-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes478-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1854-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes389-16-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1144-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1332-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes218-38-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1863-15-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-200-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes157-19-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes573-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-560-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-280-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-240-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1839-68-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes246-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes67-193-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1614-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1778-200-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1086-307-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1215-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1155-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes855-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1274-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1293-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes915-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1552-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1377-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1215-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1753-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1747-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes923-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1086-280-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1916-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes739-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1959-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes412-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-280-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes169-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1777-20-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1972-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes761-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes584-25-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes568-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1629-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1302-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1540-400-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes289-26-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes180-15-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1955-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1718-16-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes826-12-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes800-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1254-17-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes814-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes570-160-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1617-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1123-15-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1238-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes535-22-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes972-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1778-240-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes524-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1278-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes945-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes949-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1629-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes724-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-480-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1932-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes125-18-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1716-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes958-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes132-120-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes192-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1423-154-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes255-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes236-18-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1468-24-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes596-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1464-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1585-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1915-202-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes994-48-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes694-14-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1749-22-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1085-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1899-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1017-19-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1013-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1692-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes855-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes654-38-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes721-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes44-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes74-24-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes278-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1503-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1793-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1806-29-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-200-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes835-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes572-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes18-36-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1968-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1550-19-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1178-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1064-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1918-29-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1534-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1916-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1462-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1201-36-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes270-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes965-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1390-28-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes856-78-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1646-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes307-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1821-28-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes732-20-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes272-25-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes252-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes775-25-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1365-46-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1135-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes259-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1187-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes484-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes772-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1515-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1525-26-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1085-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes947-13-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-400-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1456-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes526-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes224-20-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes386-25-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1623-52-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes516-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1774-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes838-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes557-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes722-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes976-11-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes980-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1547-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes443-13-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-360-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1187-160-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes253-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1152-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1154-16-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes597-38-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1389-23-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1067-12-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1264-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1919-16-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes390-19-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes184-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes206-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1086-120-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1737-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1646-93-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes940-22-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-240-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1851-26-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes727-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes656-45-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1685-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1356-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1160-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes567-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes965-160-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes867-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1393-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1757-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes64-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes7-22-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes627-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-360-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1257-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1799-100-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes383-13-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes636-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes294-59-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-520-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes446-17-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1314-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1776-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1561-17-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes554-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1232-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes577-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1028-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1667-16-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes81-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-480-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes95-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1715-17-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-240-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1122-19-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes465-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1311-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1931-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes360-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-200-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1819-90-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1957-17-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1830-24-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes251-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes551-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1828-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes827-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes365-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1438-13-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1540-360-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1238-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes156-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes279-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes401-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes272-25-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes698-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes439-22-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1433-23-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes406-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes23-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1541-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes570-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes928-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1542-149-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes97-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1915-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1368-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1636-38-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1631-19-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes662-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1309-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes32-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1960-17-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes649-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-160-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1815-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes674-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes818-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1795-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes422-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes558-33-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1549-33-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1507-38-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1277-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes344-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes59-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes226-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1400-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes378-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1698-28-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes541-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1224-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1788-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes805-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1805-28-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes156-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes415-240-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes883-20-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes522-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1093-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1168-12-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1282-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1610-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1423-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes232-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-648-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes438-19-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1907-20-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes735-14-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes284-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1016-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes827-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes345-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1747-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1163-14-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes449-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes431-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1880-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes611-23-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes460-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes656-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-400-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes698-320-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1386-49-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes578-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes780-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes733-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-160-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes356-19-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1402-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1369-20-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1362-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes604-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1354-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1358-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1112-38-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1541-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes916-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1397-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1145-120-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes462-43-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1504-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1678-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes418-21-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes588-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1872-19-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1121-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1535-30-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes519-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes902-120-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes679-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1137-120-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes666-18-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1340-22-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes932-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1850-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1476-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes458-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes775-25-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes60-17-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes111-38-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes839-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1003-20-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes270-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1387-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes527-360-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes392-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes559-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1444-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes382-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1412-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes654-38-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes570-80-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1297-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes336-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1006-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1521-16-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes382-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1385-29-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1086-280-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1288-67-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1942-30-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1694-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1972-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes761-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1755-22-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1780-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes562-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1793-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes280-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes586-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes413-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1429-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1604-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes698-240-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-320-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes697-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes668-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1264-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1222-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes407-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes853-120-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1033-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1875-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes188-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes774-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1594-95-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1855-240-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1211-12-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1728-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes780-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes288-14-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes836-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1307-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1630-12-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes910-38-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1585-18-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1700-22-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1261-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1723-22-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1836-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1000-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1169-37-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes173-23-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes892-15-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes264-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-280-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes577-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1846-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes840-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1689-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1630-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1463-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1745-16-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1230-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-480-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1367-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1086-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1459-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1116-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes156-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1443-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes403-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes156-320-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1542-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1316-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1657-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1856-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1566-15-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes432-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1954-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1540-360-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes463-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1146-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes938-39-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes442-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1259-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1288-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-320-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1557-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1293-55-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1423-154-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes34-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes953-13-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1543-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1863-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1767-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1543-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1831-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes772-13-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes35-12-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes422-240-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1630-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-410-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes776-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1606-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes422-280-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-480-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes698-200-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1243-16-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes341-39-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes725-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1266-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes924-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1883-54-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes12-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1628-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1600-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes173-23-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1383-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes641-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1623-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes760-23-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1858-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1052-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1208-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes584-25-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1484-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1171-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes190-23-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1097-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes656-45-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1384-160-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes341-39-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes894-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes375-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes361-23-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes497-27-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes646-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1145-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-240-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-320-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes156-200-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1033-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1462-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1913-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1877-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes599-20-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1511-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes27-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1273-27-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1934-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-511-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes815-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes751-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes857-12-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1905-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes150-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes930-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes853-120-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1895-76-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes317-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes633-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1312-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1346-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1175-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes273-27-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes845-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1795-120-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes888-17-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1595-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes899-12-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes499-21-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1105-120-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1907-20-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes481-120-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1396-32-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes644-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes666-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes821-38-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes321-31-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes858-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes281-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes934-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes192-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes507-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-480-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes464-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes456-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1929-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes739-138-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes567-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-320-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1964-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes856-78-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-548-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes698-200-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1899-124-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes98-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1534-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes177-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes202-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1049-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1171-221-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes680-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1183-71-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1042-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1683-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1423-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1033-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes912-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes654-38-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1517-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1317-26-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes17-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes437-11-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes644-120-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1946-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1774-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes432-94-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1889-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes588-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes641-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1154-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes609-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1082-13-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1786-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes154-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes657-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1961-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1704-23-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1449-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes765-23-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes305-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1077-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes267-21-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes902-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1345-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1908-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1236-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes319-43-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1471-7-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes242-21-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1171-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes976-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes741-17-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1518-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes411-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes251-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1287-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes739-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes645-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes175-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes538-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes743-16-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes586-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1623-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes296-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1425-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes357-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes690-13-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes965-176-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes914-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes131-19-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1425-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1311-14-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes471-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1430-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes315-160-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1338-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1422-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes652-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes608-31-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes30-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1013-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1335-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1129-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes539-30-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes613-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1498-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1039-24-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes957-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes98-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1236-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1234-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes944-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1835-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1390-28-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes226-12-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1770-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes698-200-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes576-12-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1455-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes507-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes132-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes169-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes159-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes410-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes67-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes703-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes941-38-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes789-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-410-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1653-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-360-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1220-19-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes916-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-320-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1741-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes44-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes496-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1315-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes921-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1717-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes487-38-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes40-160-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1047-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes697-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1070-24-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1071-38-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1016-81-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes964-21-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-160-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes356-19-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes902-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1171-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1440-15-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1009-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes766-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1610-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes796-11-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1884-23-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1724-54-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes575-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1027-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes224-20-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes332-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1601-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes231-120-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes964-21-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes165-6-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes860-96-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes97-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes173-23-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1121-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes69-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1608-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes916-120-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1656-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1502-38-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1540-320-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes304-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes714-16-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes126-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes527-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1342-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1002-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1477-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes710-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1739-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1500-17-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1424-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1427-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes937-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-320-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1571-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes628-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1795-134-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1278-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1486-30-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes600-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes755-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1281-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes132-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes788-18-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1232-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1468-24-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1326-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1823-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1652-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes448-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes705-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1433-23-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes813-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1087-35-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes739-138-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes166-16-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1138-9-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1289-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1893-8-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1120-22-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes489-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes817-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-440-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes981-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1365-46-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1456-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes449-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes28-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1828-136-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1170-10-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes319-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1662-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes268-24-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1451-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1915-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1646-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes944-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1759-200-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes631-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1595-15-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1411-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1042-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1295-17-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1271-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1193-5-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes825-16-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes527-280-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes698-280-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes103-6-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes171-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1190-21-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes437-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes402-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1679-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1367-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes577-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1246-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1920-160-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1428-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes790-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes929-24-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1576-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1555-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1173-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1958-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes378-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes660-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1150-18-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes112-30-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1959-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes113-38-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1070-24-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1279-37-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes103-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes569-15-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1640-30-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes850-10-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1928-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/TEL-04768277488_5860065930_20150206182059.wav.txt data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1730-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1440-15-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1755-22-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/e1303520161109140614.wav.txt data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1363-13-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes144-23-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes649-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes548-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes78-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/e0707220161109144248.wav.txt.v0-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-200-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1873-23-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes863-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes819-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1534-186-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1894-9-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1086-160-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1524-9-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1472-14-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1015-17-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-40-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes545-13-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1028-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes328-41-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1333-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1601-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes672-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1603-12-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1643-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes838-11-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1500-17-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes676-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1831-10-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-560-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes436-21-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes307-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes495-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1693-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes180-15-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes343-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1187-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1700-22-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1490-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1738-33-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes333-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes594-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1774-160-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1594-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1821-28-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1256-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes203-7-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1683-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1422-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1153-80-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1542-149-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes442-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-120-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1637-13-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes641-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes358-20-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1915-120-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes642-30-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes353-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes99-3-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes968-14-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1007-320-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1365-46-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes103-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes291-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes479-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1773-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1043-23-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes475-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1891-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes195-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1756-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes993-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1536-5-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1370-40-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1410-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes24-18-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes829-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes284-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-280-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes854-5-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes479-11-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes482-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes74-24-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1936-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes612-15-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1171-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1313-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes520-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes655-13-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1005-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes450-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes698-320-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes636-8-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes573-15-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes129-11-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1944-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes681-80-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1753-7-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes132-160-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes293-539-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1077-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1287-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1860-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes78-40-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes230-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes615-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes771-4-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes804-3-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes916-200-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes698-200-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1288-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes297-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes801-240-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes217-26-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes996-11-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1022-360-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes538-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1361-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1221-8-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1798-4-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1294-19-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes984-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1620-4-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1262-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes591-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes805-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes15-9-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1604-80-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes739-80-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes205-28-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes200-23-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1425-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1152-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes425-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes156-160-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1387-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes899-12-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes908-18-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes414-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes704-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes281-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1174-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes950-14-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes760-23-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1324-18-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes731-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes571-8-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1570-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes552-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes916-40-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1119-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes782-7-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes386-25-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes874-4-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes217-26-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes141-13-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1928-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes883-20-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1796-6-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1021-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes934-9-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes464-6-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1698-28-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1899-120-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1102-3-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes372-11-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes971-21-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes930-3-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1308-38-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1167-5-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1549-33-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1715-17-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1898-7-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1292-14-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes815-10-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1049-6-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes138-16-3 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes370-10-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1131-3-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes193-5-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes894-280-4 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1874-4-2 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1712-29-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1370-40-1 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes1946-8-0 data/dmnYesHasInsEval
mv -i data/dmnYesHasInsTrain/genYes694-14-3 data/dmnYesHasInsEval
